### ISSUE TITLE
Q: What about 4xx error codes ?

### ISSUE THREAD

**Issue by vexy** [tareksabry1337/SwiftConnect#2]
https://github.com/tareksabry1337/SwiftConnect/blob/17705fe0aac628457e052397e5abedc12818b288/SwiftConnect/Classes/Connect.swift#L67

Here we do a check if a response is in `200..<300` range or pass `nil` otherwise.

Some (_valid_) `4xx` HTTP responses might be helpful for upper layer code structures - in terms of taking responsibility of handling them, for example famous [401 Unauthorized](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401). I suggest slightly altering (or expanding) checking error range here, to accommodate handling of such cases.

Also, just encoding the response here would be enough to align with the philosophy to "_separate class concerns_", in my opinion. Rest of the decision logic of what's "valid or not", shouldn't be responsibility of `Connect` class. What do you think ?
https://github.com/tareksabry1337/SwiftConnect/blob/17705fe0aac628457e052397e5abedc12818b288/SwiftConnect/Classes/Connect.swift#L68-L69

**Comment by tareksabry1337** [comment]
The 401 case will be handled 100% in the future it's upcoming on my notes, but it won't be responsibility of Connect either, it's going to be ConnectMiddleware which will intercept the request in case of 401 in order to trigger the refresh token scenario, I'm still thinking of an ideal way to do this as generic as possible.
One thing that can be done to improve this is not only pass the errors dictionary to the end user but also pass the status code. Then it's up for one's to decide whether it's valid or not.

For the second point it's totally valid that entire logic could be moved to the ErrorHandler class.

**Comment by vexy** [comment]
> ..it's going to be ConnectMiddleware which will intercept the request in case of 401 in order to trigger the refresh token scenario.
You're reading my mind here 😄  Was about to add, that IMHO, it _should_ be placed somewhere in middleware layer.

Structurally speaking `ConnectMiddleware` should allow some kind of "inheritance" model (rather than provide generic solution) - as a it may server different "connect" purposes. I'm thinking in direction of a _base class_, better yet "a protocol", that can be used to expand lower-layer connect functionality. Something in direction of having combo of abstract/concrete classes handling separately `sockets` and "pure" `http(s)` requests. Down the road of course 😄 

This, I believe, fits well with idea of:
> ..which will intercept the request **in case** of 401 in order to trigger the refresh token scenario

**Comment by tareksabry1337** [comment]
Yep, there's definitely plenty of room for improvements here !
